name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Reinstall Node Modules
      run: |
        cd backend
        rm -rf node_modules
        npm install

    - name: Lint code
      run: |
        cd backend
        npm run lint

    - name: Run the tests
      run: |
        cd backend
        npm test

    - name: Build the Docker image
      run: |
        cd backend
        docker build -t seth001/backend .

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push seth001/backend:latest