name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Navigate to backend directory
      run: cd backend

    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Lint code
      run: npm run lint
      working-directory: backend

    - name: Run the tests
      run: npm test
      working-directory: backend

    - name: Build the Docker image
      run: docker build -t your-dockerhub-username/backend backend

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push your-dockerhub-username/backend